#
# Module manifest for module 'Eigenverft.Manifested.Drydock'
#
# Generated by: Eigenverft
#
# Generated on: 10/06/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Eigenverft.Manifested.Drydock.psm1'

# Version number of this module.
ModuleVersion = '0.20255.64141'

# Supported PSEditions
CompatiblePSEditions = @('Desktop','Core')

# ID used to uniquely identify this module
GUID = '8A19EC94-84E6-4029-B38E-188629E525C6'

# Author of this module
Author = 'Eigenverft'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = 'Copyright (c) 2025 Eigenverft'

# Description of the functionality provided by this module
Description = 'PowerShell helper functions for the Eigenverft Manifested Drydock, optimized for lightning-fast iteration and reliable local + CI/CD workflows. Expect frequent releases—auto-versioning is built in. Tasks are parity-driven: the same commands run locally and in CI/CD, so local builds remain fully functional even if the pipeline is down.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @(@{ModuleName = 'OtherModule'; ModuleVersion = '0.20255.64141'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # ...Deployments.ps1
    'Convert-BranchToDeploymentInfo',
    
    # ...Dotnet.ps1
    'Enable-TempDotnetTools',
    'Disable-TempDotnetTools',
    'Register-LocalNuGetDotNetPackageSource',
    'Unregister-LocalNuGetDotNetPackageSource',

    # ...Execution.ps1
    'Invoke-Exec',

    # ...Git.ps1
    'Get-GitTopLevelDirectory',
    'Get-GitCurrentBranch',
    'Get-GitCurrentBranchRoot',
    'Get-GitRepositoryName',
    'Get-GitRemoteUrl',
    'Invoke-GitAddCommitPush',

    # ...IO.ps1
    'Find-FilesByPattern',
    'Find-TreeContent',
    'Find-TreeContentByFile',
    'Resolve-ModulePath',

    # ...Logging.ps1
    'Write-ConsoleLog',

    # ...Powershell.ps1
    'Initialize-PowerShellMiniBootstrap',
    'Import-Script',
    'Use-Tls12',
    'Export-OfflineModuleBundle',
    'Uninstall-PreviousModuleVersions',
    'Find-ModuleScopeClutter',
    'Update-ManifestModuleVersion',
    'Update-ManifestReleaseNotes',
    'Update-ManifestPrerelease',
    'Register-LocalPSGalleryRepository',
    'Unregister-LocalPSGalleryRepository',

    'Register-DefaultNuGetPackageSource',
    'Register-LocalNuGetPackageSource',
    'Unregister-LocalNuGetPackageSource',
    
    # ...Process.ps1
    'Open-LocalHtml',

    # ...Drydock.ps1
    'Get-ConfigValue',
    'Get-RunEnvironment',
    'Drydock',
    
    # ...ScheduledTask.ps1
    'New-CompatScheduledTask',

    # ...Tests.ps1
    'Test-VariableValue',
    'Test-CommandAvailable',
    'Test-ModuleAvailable',
    'Test-PsGalleryPublishPrereqsOffline',

    # ...Version.ps1
    'Convert-DateTimeTo64SecVersionComponents',
    'Convert-64SecVersionComponentsToDateTime',
    'Convert-DateTimeTo64SecPowershellVersion',
    'Convert-64SecPowershellVersionToDateTime'
    )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'ggtd',
    'ggcb',
    'ggcbr',
    'ggrn',
    'gru',
    'igacp',

    'cdv64',
    'cdv64r',
    'cdv64ps',
    'cdv64psr',

    'iexec',
    
    'ummv',

    'ffbp',
    'tvv',
    'gre',
    'gcv'
    )

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Eigenverft', 'Manifested', "Drydock", 'Powershell'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/eigenverft/Eigenverft.Manifested.Drydock/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/eigenverft/Eigenverft.Manifested.Drydock'
                   
        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/eigenverft/Eigenverft.Manifested.Drydock/refs/heads/main/resources/eigenverft-logo-v7-harbor-square_128_128.png'

        # ReleaseNotes of this module
        ReleaseNotes = ''

        # Prerelease string of this module
        Prerelease = 'dev'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
